-- =============================================================================
-- Seed script for Freshers Hiring Platform
-- Idempotent: safe to run multiple times (uses ON CONFLICT DO NOTHING)
-- =============================================================================

-- Add unique constraint for idempotent seeding
ALTER TABLE colleges ADD CONSTRAINT colleges_name_unique UNIQUE (name);

-- =============================================================================
-- Skills seed
-- =============================================================================
INSERT INTO skills (name, category) VALUES
  ('Python', 'Technical'),
  ('Java', 'Technical'),
  ('Web Development', 'Technical'),
  ('UI/UX Design', 'Design'),
  ('Content Writing', 'Creative'),
  ('Influencer Marketing', 'Marketing'),
  ('Sales/Outreach', 'Business'),
  ('Data Analysis', 'Technical'),
  ('Operations', 'Business'),
  ('Product Thinking', 'Business'),
  ('Communication', 'Soft Skills')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 1: IITs (23)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  ('IIT Bombay', 1, 'Maharashtra', 'IIT'),
  ('IIT Delhi', 1, 'Delhi', 'IIT'),
  ('IIT Madras', 1, 'Tamil Nadu', 'IIT'),
  ('IIT Kanpur', 1, 'Uttar Pradesh', 'IIT'),
  ('IIT Kharagpur', 1, 'West Bengal', 'IIT'),
  ('IIT Roorkee', 1, 'Uttarakhand', 'IIT'),
  ('IIT Guwahati', 1, 'Assam', 'IIT'),
  ('IIT Hyderabad', 1, 'Telangana', 'IIT'),
  ('IIT Indore', 1, 'Madhya Pradesh', 'IIT'),
  ('IIT BHU Varanasi', 1, 'Uttar Pradesh', 'IIT'),
  ('IIT Ropar', 1, 'Punjab', 'IIT'),
  ('IIT Bhubaneswar', 1, 'Odisha', 'IIT'),
  ('IIT Gandhinagar', 1, 'Gujarat', 'IIT'),
  ('IIT Patna', 1, 'Bihar', 'IIT'),
  ('IIT Jodhpur', 1, 'Rajasthan', 'IIT'),
  ('IIT Mandi', 1, 'Himachal Pradesh', 'IIT'),
  ('IIT Tirupati', 1, 'Andhra Pradesh', 'IIT'),
  ('IIT Palakkad', 1, 'Kerala', 'IIT'),
  ('IIT Dharwad', 1, 'Karnataka', 'IIT'),
  ('IIT Bhilai', 1, 'Chhattisgarh', 'IIT'),
  ('IIT Goa', 1, 'Goa', 'IIT'),
  ('IIT Jammu', 1, 'Jammu & Kashmir', 'IIT'),
  ('IIT (ISM) Dhanbad', 1, 'Jharkhand', 'IIT')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 1: NITs (31)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  ('NIT Trichy', 1, 'Tamil Nadu', 'NIT'),
  ('NIT Surathkal', 1, 'Karnataka', 'NIT'),
  ('NIT Warangal', 1, 'Telangana', 'NIT'),
  ('NIT Calicut', 1, 'Kerala', 'NIT'),
  ('NIT Rourkela', 1, 'Odisha', 'NIT'),
  ('NIT Allahabad (MNNIT)', 1, 'Uttar Pradesh', 'NIT'),
  ('NIT Kurukshetra', 1, 'Haryana', 'NIT'),
  ('NIT Jaipur (MNIT)', 1, 'Rajasthan', 'NIT'),
  ('NIT Nagpur (VNIT)', 1, 'Maharashtra', 'NIT'),
  ('NIT Durgapur', 1, 'West Bengal', 'NIT'),
  ('NIT Hamirpur', 1, 'Himachal Pradesh', 'NIT'),
  ('NIT Silchar', 1, 'Assam', 'NIT'),
  ('NIT Srinagar', 1, 'Jammu & Kashmir', 'NIT'),
  ('NIT Jalandhar', 1, 'Punjab', 'NIT'),
  ('NIT Patna', 1, 'Bihar', 'NIT'),
  ('NIT Raipur', 1, 'Chhattisgarh', 'NIT'),
  ('NIT Agartala', 1, 'Tripura', 'NIT'),
  ('NIT Arunachal Pradesh', 1, 'Arunachal Pradesh', 'NIT'),
  ('NIT Delhi', 1, 'Delhi', 'NIT'),
  ('NIT Goa', 1, 'Goa', 'NIT'),
  ('NIT Manipur', 1, 'Manipur', 'NIT'),
  ('NIT Meghalaya', 1, 'Meghalaya', 'NIT'),
  ('NIT Mizoram', 1, 'Mizoram', 'NIT'),
  ('NIT Nagaland', 1, 'Nagaland', 'NIT'),
  ('NIT Puducherry', 1, 'Puducherry', 'NIT'),
  ('NIT Sikkim', 1, 'Sikkim', 'NIT'),
  ('NIT Surat (SVNIT)', 1, 'Gujarat', 'NIT'),
  ('NIT Jamshedpur', 1, 'Jharkhand', 'NIT'),
  ('NIT Bhopal (MANIT)', 1, 'Madhya Pradesh', 'NIT'),
  ('NIT Uttarakhand', 1, 'Uttarakhand', 'NIT'),
  ('NIT Andhra Pradesh', 1, 'Andhra Pradesh', 'NIT')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 1: IIITs (26)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  ('IIIT Hyderabad', 1, 'Telangana', 'IIIT'),
  ('IIIT Allahabad', 1, 'Uttar Pradesh', 'IIIT'),
  ('IIIT Delhi', 1, 'Delhi', 'IIIT'),
  ('IIIT Bangalore', 1, 'Karnataka', 'IIIT'),
  ('IIIT Jabalpur', 1, 'Madhya Pradesh', 'IIIT'),
  ('IIIT Gwalior', 1, 'Madhya Pradesh', 'IIIT'),
  ('IIIT Kancheepuram', 1, 'Tamil Nadu', 'IIIT'),
  ('IIIT Kottayam', 1, 'Kerala', 'IIIT'),
  ('IIIT Lucknow', 1, 'Uttar Pradesh', 'IIIT'),
  ('IIIT Manipur', 1, 'Manipur', 'IIIT'),
  ('IIIT Nagpur', 1, 'Maharashtra', 'IIIT'),
  ('IIIT Pune', 1, 'Maharashtra', 'IIIT'),
  ('IIIT Ranchi', 1, 'Jharkhand', 'IIIT'),
  ('IIIT Sonepat', 1, 'Haryana', 'IIIT'),
  ('IIIT Sri City', 1, 'Andhra Pradesh', 'IIIT'),
  ('IIIT Surat', 1, 'Gujarat', 'IIIT'),
  ('IIIT Tiruchirappalli', 1, 'Tamil Nadu', 'IIIT'),
  ('IIIT Una', 1, 'Himachal Pradesh', 'IIIT'),
  ('IIIT Vadodara', 1, 'Gujarat', 'IIIT'),
  ('IIIT Agartala', 1, 'Tripura', 'IIIT'),
  ('IIIT Bhagalpur', 1, 'Bihar', 'IIIT'),
  ('IIIT Bhopal', 1, 'Madhya Pradesh', 'IIIT'),
  ('IIIT Dharwad', 1, 'Karnataka', 'IIIT'),
  ('IIIT Kalyani', 1, 'West Bengal', 'IIIT'),
  ('IIIT Kurnool', 1, 'Andhra Pradesh', 'IIIT'),
  ('IIIT Raichur', 1, 'Karnataka', 'IIIT')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 1: BITS & IISc (5)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  ('BITS Pilani', 1, 'Rajasthan', 'BITS'),
  ('BITS Pilani Goa', 1, 'Goa', 'BITS'),
  ('BITS Pilani Hyderabad', 1, 'Telangana', 'BITS'),
  ('BITS Pilani Dubai', 1, 'Rajasthan', 'BITS'),
  ('IISc Bangalore', 1, 'Karnataka', 'IISc')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 2 (250+ real Indian colleges)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  -- Major Private Universities
  ('VIT Vellore', 2, 'Tamil Nadu', 'Private'),
  ('VIT Chennai', 2, 'Tamil Nadu', 'Private'),
  ('VIT Bhopal', 2, 'Madhya Pradesh', 'Private'),
  ('VIT AP', 2, 'Andhra Pradesh', 'Private'),
  ('SRM Institute of Science and Technology Chennai', 2, 'Tamil Nadu', 'Private'),
  ('SRM University AP', 2, 'Andhra Pradesh', 'Private'),
  ('SRM University Sonepat', 2, 'Haryana', 'Private'),
  ('Manipal Institute of Technology', 2, 'Karnataka', 'Private'),
  ('Manipal University Jaipur', 2, 'Rajasthan', 'Private'),
  ('Amity University Noida', 2, 'Uttar Pradesh', 'Private'),
  ('Amity University Lucknow', 2, 'Uttar Pradesh', 'Private'),
  ('Amity University Jaipur', 2, 'Rajasthan', 'Private'),
  ('Amity University Mumbai', 2, 'Maharashtra', 'Private'),
  ('Amity University Gwalior', 2, 'Madhya Pradesh', 'Private'),
  ('Amity University Kolkata', 2, 'West Bengal', 'Private'),
  ('Christ University Bangalore', 2, 'Karnataka', 'Private'),
  ('KIIT Bhubaneswar', 2, 'Odisha', 'Private'),
  ('Thapar Institute of Engineering and Technology Patiala', 2, 'Punjab', 'Private'),
  ('PEC Chandigarh', 2, 'Chandigarh', 'State'),
  ('DTU Delhi', 2, 'Delhi', 'State'),
  ('NSUT Delhi', 2, 'Delhi', 'State'),
  ('COEP Pune', 2, 'Maharashtra', 'State'),
  ('BIT Mesra', 2, 'Jharkhand', 'Private'),
  ('PSG College of Technology Coimbatore', 2, 'Tamil Nadu', 'Private'),
  ('MIT Manipal', 2, 'Karnataka', 'Private'),
  ('Symbiosis Institute of Technology Pune', 2, 'Maharashtra', 'Private'),
  ('LNM Institute of Information Technology Jaipur', 2, 'Rajasthan', 'Private'),
  ('IIITM Gwalior', 2, 'Madhya Pradesh', 'State'),
  ('Jadavpur University', 2, 'West Bengal', 'State'),
  ('Anna University Chennai', 2, 'Tamil Nadu', 'State'),
  ('Savitribai Phule Pune University', 2, 'Maharashtra', 'State'),
  ('University of Hyderabad', 2, 'Telangana', 'State'),
  ('Jamia Millia Islamia Delhi', 2, 'Delhi', 'State'),
  ('Aligarh Muslim University', 2, 'Uttar Pradesh', 'State'),
  ('BHU Institute of Technology', 2, 'Uttar Pradesh', 'State'),
  ('University of Delhi', 2, 'Delhi', 'State'),
  ('Presidency University Bangalore', 2, 'Karnataka', 'Private'),
  ('Shiv Nadar University', 2, 'Uttar Pradesh', 'Private'),
  ('Ashoka University', 2, 'Haryana', 'Private'),
  ('FLAME University Pune', 2, 'Maharashtra', 'Private'),
  ('OP Jindal Global University', 2, 'Haryana', 'Private'),
  ('Bennett University Greater Noida', 2, 'Uttar Pradesh', 'Private'),
  ('Plaksha University Mohali', 2, 'Punjab', 'Private'),
  ('IIIT Sri City', 2, 'Andhra Pradesh', 'Private'),
  ('Lovely Professional University Jalandhar', 2, 'Punjab', 'Private'),
  ('Chandigarh University', 2, 'Punjab', 'Private'),
  ('Chitkara University Rajpura', 2, 'Punjab', 'Private'),
  ('Shoolini University Solan', 2, 'Himachal Pradesh', 'Private'),
  ('UPES Dehradun', 2, 'Uttarakhand', 'Private'),
  ('DIT University Dehradun', 2, 'Uttarakhand', 'Private'),
  ('Graphic Era University Dehradun', 2, 'Uttarakhand', 'Private'),
  ('Nirma University Ahmedabad', 2, 'Gujarat', 'Private'),
  ('DA-IICT Gandhinagar', 2, 'Gujarat', 'Private'),
  ('Pandit Deendayal Energy University Gandhinagar', 2, 'Gujarat', 'Private'),
  ('Charotar University of Science and Technology Anand', 2, 'Gujarat', 'Private'),
  ('DAIICT Gandhinagar', 2, 'Gujarat', 'Private'),
  ('Dhirubhai Ambani Institute Gandhinagar', 2, 'Gujarat', 'Private'),
  ('LDRP Institute of Technology and Research Gandhinagar', 2, 'Gujarat', 'Private'),
  ('MS Ramaiah Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('RV College of Engineering Bangalore', 2, 'Karnataka', 'Private'),
  ('BMS College of Engineering Bangalore', 2, 'Karnataka', 'Private'),
  ('PES University Bangalore', 2, 'Karnataka', 'Private'),
  ('Dayananda Sagar College of Engineering Bangalore', 2, 'Karnataka', 'Private'),
  ('New Horizon College of Engineering Bangalore', 2, 'Karnataka', 'Private'),
  ('Nitte Meenakshi Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('JSS Science and Technology University Mysuru', 2, 'Karnataka', 'Private'),
  ('SDM College of Engineering and Technology Dharwad', 2, 'Karnataka', 'Private'),
  ('KLE Technological University Hubli', 2, 'Karnataka', 'Private'),
  ('NMAM Institute of Technology Nitte', 2, 'Karnataka', 'Private'),
  ('Siddaganga Institute of Technology Tumkur', 2, 'Karnataka', 'Private'),
  ('BV Bhoomaraddi College of Engineering Hubli', 2, 'Karnataka', 'Private'),
  ('MIT World Peace University Pune', 2, 'Maharashtra', 'Private'),
  ('Vishwakarma Institute of Technology Pune', 2, 'Maharashtra', 'Private'),
  ('Pune Institute of Computer Technology', 2, 'Maharashtra', 'Private'),
  ('College of Engineering Pune', 2, 'Maharashtra', 'State'),
  ('Walchand College of Engineering Sangli', 2, 'Maharashtra', 'State'),
  ('VJTI Mumbai', 2, 'Maharashtra', 'State'),
  ('Sardar Patel Institute of Technology Mumbai', 2, 'Maharashtra', 'Private'),
  ('DJ Sanghvi College of Engineering Mumbai', 2, 'Maharashtra', 'Private'),
  ('KJ Somaiya College of Engineering Mumbai', 2, 'Maharashtra', 'Private'),
  ('Thadomal Shahani Engineering College Mumbai', 2, 'Maharashtra', 'Private'),
  ('Fr. Conceicao Rodrigues College of Engineering Mumbai', 2, 'Maharashtra', 'Private'),
  ('Dwarkadas J Sanghvi College Mumbai', 2, 'Maharashtra', 'Private'),
  ('Ramrao Adik Institute of Technology Navi Mumbai', 2, 'Maharashtra', 'Private'),
  ('Bharati Vidyapeeth Deemed University Pune', 2, 'Maharashtra', 'Deemed'),
  ('SRM University Ramapuram', 2, 'Tamil Nadu', 'Private'),
  ('SSN College of Engineering Chennai', 2, 'Tamil Nadu', 'Private'),
  ('CEG Anna University Chennai', 2, 'Tamil Nadu', 'State'),
  ('Madras Institute of Technology Chennai', 2, 'Tamil Nadu', 'State'),
  ('Thiagarajar College of Engineering Madurai', 2, 'Tamil Nadu', 'Private'),
  ('Kumaraguru College of Technology Coimbatore', 2, 'Tamil Nadu', 'Private'),
  ('Kongu Engineering College Erode', 2, 'Tamil Nadu', 'Private'),
  ('Bannari Amman Institute of Technology Sathyamangalam', 2, 'Tamil Nadu', 'Private'),
  ('Mepco Schlenk Engineering College Sivakasi', 2, 'Tamil Nadu', 'Private'),
  ('Sri Sivasubramaniya Nadar College Chennai', 2, 'Tamil Nadu', 'Private'),
  ('Rajalakshmi Engineering College Chennai', 2, 'Tamil Nadu', 'Private'),
  ('St. Josephs College of Engineering Chennai', 2, 'Tamil Nadu', 'Private'),
  ('Sathyabama Institute of Science and Technology Chennai', 2, 'Tamil Nadu', 'Deemed'),
  ('Karunya Institute of Technology Coimbatore', 2, 'Tamil Nadu', 'Deemed'),
  ('Hindustan Institute of Technology Chennai', 2, 'Tamil Nadu', 'Deemed'),
  ('Kalasalingam Academy of Research and Education Srivilliputtur', 2, 'Tamil Nadu', 'Deemed'),
  ('Amrita Vishwa Vidyapeetham Coimbatore', 2, 'Tamil Nadu', 'Deemed'),
  ('Amrita Vishwa Vidyapeetham Amritapuri', 2, 'Kerala', 'Deemed'),
  ('Amrita Vishwa Vidyapeetham Bengaluru', 2, 'Karnataka', 'Deemed'),
  ('National Institute of Engineering Mysuru', 2, 'Karnataka', 'Private'),
  ('Government Engineering College Thrissur', 2, 'Kerala', 'State'),
  ('College of Engineering Trivandrum', 2, 'Kerala', 'State'),
  ('TKM College of Engineering Kollam', 2, 'Kerala', 'Private'),
  ('Model Engineering College Kochi', 2, 'Kerala', 'State'),
  ('Rajagiri School of Engineering and Technology Kochi', 2, 'Kerala', 'Private'),
  ('Mar Athanasius College of Engineering Kothamangalam', 2, 'Kerala', 'Private'),
  ('Government College of Technology Coimbatore', 2, 'Tamil Nadu', 'State'),
  ('National Engineering College Kovilpatti', 2, 'Tamil Nadu', 'Private'),
  ('Velammal Engineering College Chennai', 2, 'Tamil Nadu', 'Private'),
  ('Kalinga Institute of Industrial Technology Bhubaneswar', 2, 'Odisha', 'Deemed'),
  ('Silicon Institute of Technology Bhubaneswar', 2, 'Odisha', 'Private'),
  ('CET Bhubaneswar', 2, 'Odisha', 'State'),
  ('IIIT Bhubaneswar', 2, 'Odisha', 'State'),
  ('SOA University Bhubaneswar', 2, 'Odisha', 'Deemed'),
  ('IGIT Sarang', 2, 'Odisha', 'State'),
  ('VSSUT Burla', 2, 'Odisha', 'State'),
  ('Heritage Institute of Technology Kolkata', 2, 'West Bengal', 'Private'),
  ('Institute of Engineering and Management Kolkata', 2, 'West Bengal', 'Private'),
  ('Maulana Abul Kalam Azad University of Technology Kolkata', 2, 'West Bengal', 'State'),
  ('Bengal Engineering and Science University Shibpur', 2, 'West Bengal', 'State'),
  ('IIEST Shibpur', 2, 'West Bengal', 'State'),
  ('Kalyani Government Engineering College', 2, 'West Bengal', 'State'),
  ('Haldia Institute of Technology', 2, 'West Bengal', 'Private'),
  ('Techno India University Kolkata', 2, 'West Bengal', 'Private'),
  ('University of Engineering and Management Kolkata', 2, 'West Bengal', 'Private'),
  ('St. Xaviers College Kolkata', 2, 'West Bengal', 'Private'),
  ('Birla Institute of Technology Ranchi', 2, 'Jharkhand', 'Private'),
  ('BIT Sindri Dhanbad', 2, 'Jharkhand', 'State'),
  ('Central University of Jharkhand', 2, 'Jharkhand', 'State'),
  ('Motilal Nehru National Institute of Technology Allahabad', 2, 'Uttar Pradesh', 'State'),
  ('HBTU Kanpur', 2, 'Uttar Pradesh', 'State'),
  ('IET Lucknow', 2, 'Uttar Pradesh', 'State'),
  ('Jaypee Institute of Information Technology Noida', 2, 'Uttar Pradesh', 'Private'),
  ('Jaypee University of Engineering and Technology Guna', 2, 'Madhya Pradesh', 'Private'),
  ('JECRC University Jaipur', 2, 'Rajasthan', 'Private'),
  ('Malaviya National Institute of Technology Jaipur', 2, 'Rajasthan', 'State'),
  ('Birla Institute of Technology and Science Pilani', 2, 'Rajasthan', 'Private'),
  ('Manipal University Jaipur Campus', 2, 'Rajasthan', 'Private'),
  ('Poornima University Jaipur', 2, 'Rajasthan', 'Private'),
  ('IIIT Kota', 2, 'Rajasthan', 'State'),
  ('Government Engineering College Ajmer', 2, 'Rajasthan', 'State'),
  ('MBM University Jodhpur', 2, 'Rajasthan', 'State'),
  ('Jaipur Engineering College and Research Centre', 2, 'Rajasthan', 'Private'),
  ('Global Institute of Technology Jaipur', 2, 'Rajasthan', 'Private'),
  ('GLA University Mathura', 2, 'Uttar Pradesh', 'Private'),
  ('JIIT Noida', 2, 'Uttar Pradesh', 'Private'),
  ('Galgotias University Greater Noida', 2, 'Uttar Pradesh', 'Private'),
  ('SRM Institute of Science and Technology Ghaziabad', 2, 'Uttar Pradesh', 'Private'),
  ('Integral University Lucknow', 2, 'Uttar Pradesh', 'Private'),
  ('Babu Banarasi Das University Lucknow', 2, 'Uttar Pradesh', 'Private'),
  ('AKTU Lucknow', 2, 'Uttar Pradesh', 'State'),
  ('Chandigarh College of Engineering and Technology', 2, 'Chandigarh', 'State'),
  ('Punjab Engineering College Chandigarh', 2, 'Chandigarh', 'State'),
  ('Guru Nanak Dev University Amritsar', 2, 'Punjab', 'State'),
  ('Punjabi University Patiala', 2, 'Punjab', 'State'),
  ('DAV Institute of Engineering and Technology Jalandhar', 2, 'Punjab', 'Private'),
  ('Guru Gobind Singh Indraprastha University Delhi', 2, 'Delhi', 'State'),
  ('IGDTUW Delhi', 2, 'Delhi', 'State'),
  ('Jamia Hamdard Delhi', 2, 'Delhi', 'Deemed'),
  ('TERI School of Advanced Studies Delhi', 2, 'Delhi', 'Deemed'),
  ('Netaji Subhas University of Technology Delhi', 2, 'Delhi', 'State'),
  ('BML Munjal University Gurugram', 2, 'Haryana', 'Private'),
  ('Manav Rachna International Institute of Research Faridabad', 2, 'Haryana', 'Deemed'),
  ('YMCA University of Science and Technology Faridabad', 2, 'Haryana', 'State'),
  ('NorthCap University Gurugram', 2, 'Haryana', 'Private'),
  ('JC Bose University of Science and Technology Faridabad', 2, 'Haryana', 'State'),
  ('Kurukshetra University', 2, 'Haryana', 'State'),
  ('Deenbandhu Chhotu Ram University Murthal', 2, 'Haryana', 'State'),
  ('UIET Chandigarh', 2, 'Chandigarh', 'State'),
  ('Panjab University Chandigarh', 2, 'Chandigarh', 'State'),
  ('Jaypee University of Information Technology Solan', 2, 'Himachal Pradesh', 'Private'),
  ('NIT Hamirpur', 2, 'Himachal Pradesh', 'State'),
  ('IIT Mandi Kamand', 2, 'Himachal Pradesh', 'State'),
  ('Himachal Pradesh University Shimla', 2, 'Himachal Pradesh', 'State'),
  ('University of Jammu', 2, 'Jammu & Kashmir', 'State'),
  ('University of Kashmir', 2, 'Jammu & Kashmir', 'State'),
  ('Cluster University Srinagar', 2, 'Jammu & Kashmir', 'State'),
  ('IK Gujral Punjab Technical University Jalandhar', 2, 'Punjab', 'State'),
  ('SLIET Longowal', 2, 'Punjab', 'State'),
  ('Cochin University of Science and Technology', 2, 'Kerala', 'State'),
  ('CUSAT Kochi', 2, 'Kerala', 'State'),
  ('Kerala University Trivandrum', 2, 'Kerala', 'State'),
  ('Mahatma Gandhi University Kottayam', 2, 'Kerala', 'State'),
  ('LBS College of Engineering Kasaragod', 2, 'Kerala', 'State'),
  ('Saintgits College of Engineering Kottayam', 2, 'Kerala', 'Private'),
  ('Amal Jyothi College of Engineering Kottayam', 2, 'Kerala', 'Private'),
  ('Jyothy Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('CMR Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('Ramaiah University of Applied Sciences Bangalore', 2, 'Karnataka', 'Private'),
  ('Alliance University Bangalore', 2, 'Karnataka', 'Private'),
  ('Reva University Bangalore', 2, 'Karnataka', 'Private'),
  ('BNM Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('Sir M Visvesvaraya Institute of Technology Bangalore', 2, 'Karnataka', 'Private'),
  ('University Visvesvaraya College of Engineering Bangalore', 2, 'Karnataka', 'State'),
  ('Bangalore Institute of Technology', 2, 'Karnataka', 'Private'),
  ('DSCE Bangalore', 2, 'Karnataka', 'Private'),
  ('Osmania University Hyderabad', 2, 'Telangana', 'State'),
  ('JNTU Hyderabad', 2, 'Telangana', 'State'),
  ('CBIT Hyderabad', 2, 'Telangana', 'Private'),
  ('Vasavi College of Engineering Hyderabad', 2, 'Telangana', 'Private'),
  ('CVR College of Engineering Hyderabad', 2, 'Telangana', 'Private'),
  ('Muffakham Jah College of Engineering Hyderabad', 2, 'Telangana', 'Private'),
  ('Gokaraju Rangaraju Institute of Engineering and Technology Hyderabad', 2, 'Telangana', 'Private'),
  ('Mahindra University Hyderabad', 2, 'Telangana', 'Private'),
  ('ICFAI Foundation for Higher Education Hyderabad', 2, 'Telangana', 'Deemed'),
  ('Anurag University Hyderabad', 2, 'Telangana', 'Private'),
  ('Vardhaman College of Engineering Hyderabad', 2, 'Telangana', 'Private'),
  ('Maturi Venkata Subba Rao Engineering College Hyderabad', 2, 'Telangana', 'Private'),
  ('JNTU Kakinada', 2, 'Andhra Pradesh', 'State'),
  ('Andhra University Visakhapatnam', 2, 'Andhra Pradesh', 'State'),
  ('GITAM Visakhapatnam', 2, 'Andhra Pradesh', 'Deemed'),
  ('KL University Vijayawada', 2, 'Andhra Pradesh', 'Deemed'),
  ('Vignan University Guntur', 2, 'Andhra Pradesh', 'Deemed'),
  ('RVR and JC College of Engineering Guntur', 2, 'Andhra Pradesh', 'Private'),
  ('Gayatri Vidya Parishad College Visakhapatnam', 2, 'Andhra Pradesh', 'Private'),
  ('SRKR Engineering College Bhimavaram', 2, 'Andhra Pradesh', 'Private'),
  ('Acharya Nagarjuna University Guntur', 2, 'Andhra Pradesh', 'State'),
  ('IIITDM Kancheepuram', 2, 'Tamil Nadu', 'State'),
  ('SASTRA University Thanjavur', 2, 'Tamil Nadu', 'Deemed'),
  ('Shanmugha Arts Science Technology and Research Academy Thanjavur', 2, 'Tamil Nadu', 'Deemed'),
  ('Vel Tech University Chennai', 2, 'Tamil Nadu', 'Private'),
  ('SRM Easwari Engineering College Chennai', 2, 'Tamil Nadu', 'Private'),
  ('Meenakshi Sundararajan Engineering College Chennai', 2, 'Tamil Nadu', 'Private'),
  ('IIT Madras Research Park', 2, 'Tamil Nadu', 'State'),
  ('CIT Coimbatore', 2, 'Tamil Nadu', 'Private'),
  ('Sri Krishna College of Technology Coimbatore', 2, 'Tamil Nadu', 'Private'),
  ('Karpagam College of Engineering Coimbatore', 2, 'Tamil Nadu', 'Private'),
  ('Coimbatore Institute of Technology', 2, 'Tamil Nadu', 'State'),
  ('RVCE Bangalore', 2, 'Karnataka', 'Private'),
  ('Visvesvaraya Technological University Belgaum', 2, 'Karnataka', 'State'),
  ('Mysore University', 2, 'Karnataka', 'State'),
  ('IISc Mathematics', 2, 'Karnataka', 'State'),
  ('Institute of Chemical Technology Mumbai', 2, 'Maharashtra', 'State'),
  ('SPCE Mumbai', 2, 'Maharashtra', 'Private'),
  ('Mukesh Patel School of Technology Mumbai', 2, 'Maharashtra', 'Private'),
  ('Pillai College of Engineering Navi Mumbai', 2, 'Maharashtra', 'Private'),
  ('Terna Engineering College Navi Mumbai', 2, 'Maharashtra', 'Private'),
  ('Vidyalankar Institute of Technology Mumbai', 2, 'Maharashtra', 'Private'),
  ('Rajiv Gandhi Institute of Technology Mumbai', 2, 'Maharashtra', 'Private'),
  ('Sinhgad College of Engineering Pune', 2, 'Maharashtra', 'Private'),
  ('Cummins College of Engineering for Women Pune', 2, 'Maharashtra', 'Private'),
  ('MAEER MIT College of Engineering Pune', 2, 'Maharashtra', 'Private'),
  ('Army Institute of Technology Pune', 2, 'Maharashtra', 'Private'),
  ('PICT Pune', 2, 'Maharashtra', 'Private'),
  ('Indira College of Engineering and Management Pune', 2, 'Maharashtra', 'Private'),
  ('Dr. Vishwanath Karad MIT World Peace University Pune', 2, 'Maharashtra', 'Private'),
  ('Shri Ramdeobaba College of Engineering Nagpur', 2, 'Maharashtra', 'Private'),
  ('Yeshwantrao Chavan College of Engineering Nagpur', 2, 'Maharashtra', 'State'),
  ('Government College of Engineering Aurangabad', 2, 'Maharashtra', 'State'),
  ('Dharmsinh Desai University Nadiad', 2, 'Gujarat', 'State'),
  ('LD College of Engineering Ahmedabad', 2, 'Gujarat', 'State'),
  ('Sardar Vallabhbhai National Institute of Technology Surat', 2, 'Gujarat', 'State'),
  ('Marwadi University Rajkot', 2, 'Gujarat', 'Private'),
  ('Gujarat Technological University Ahmedabad', 2, 'Gujarat', 'State'),
  ('Indus University Ahmedabad', 2, 'Gujarat', 'Private'),
  ('BV Patel Pharmaceutical Education Ahmedabad', 2, 'Gujarat', 'Private'),
  ('RGPV Bhopal', 2, 'Madhya Pradesh', 'State'),
  ('MANIT Bhopal', 2, 'Madhya Pradesh', 'State'),
  ('SGSITS Indore', 2, 'Madhya Pradesh', 'State'),
  ('IPS Academy Indore', 2, 'Madhya Pradesh', 'Private'),
  ('Medicaps University Indore', 2, 'Madhya Pradesh', 'Private'),
  ('Maulana Azad National Institute of Technology Bhopal', 2, 'Madhya Pradesh', 'State'),
  ('LNCT University Bhopal', 2, 'Madhya Pradesh', 'Private'),
  ('Shri Govindram Seksaria Institute of Technology Indore', 2, 'Madhya Pradesh', 'State'),
  ('National Institute of Technology Raipur', 2, 'Chhattisgarh', 'State'),
  ('CSVTU Bhilai', 2, 'Chhattisgarh', 'State'),
  ('Bhilai Institute of Technology Durg', 2, 'Chhattisgarh', 'Private'),
  ('Rungta College of Engineering Bhilai', 2, 'Chhattisgarh', 'Private'),
  ('University of Lucknow', 2, 'Uttar Pradesh', 'State'),
  ('Banaras Hindu University', 2, 'Uttar Pradesh', 'State'),
  ('IIT BHU', 2, 'Uttar Pradesh', 'State'),
  ('Maharaja Surajmal Institute of Technology Delhi', 2, 'Delhi', 'State'),
  ('Bharati Vidyapeeth College of Engineering Delhi', 2, 'Delhi', 'Private'),
  ('Ambedkar Institute of Advanced Communication Technologies Delhi', 2, 'Delhi', 'State'),
  ('Maharaja Agrasen Institute of Technology Delhi', 2, 'Delhi', 'Private')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- Colleges seed — TIER 3 (250+ real Indian colleges)
-- =============================================================================
INSERT INTO colleges (name, tier, state, type) VALUES
  -- Uttar Pradesh
  ('ABES Engineering College Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('ABES Institute of Technology Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('Ajay Kumar Garg Engineering College Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('Krishna Institute of Engineering and Technology Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('IMS Engineering College Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('Raj Kumar Goel Institute of Technology Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('RKGIT Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('Shambhunath Institute of Engineering and Technology Allahabad', 3, 'Uttar Pradesh', 'Private'),
  ('United College of Engineering and Research Allahabad', 3, 'Uttar Pradesh', 'Private'),
  ('Pranveer Singh Institute of Technology Kanpur', 3, 'Uttar Pradesh', 'Private'),
  ('Dr. Ambedkar Institute of Technology for Handicapped Kanpur', 3, 'Uttar Pradesh', 'State'),
  ('Kanpur Institute of Technology', 3, 'Uttar Pradesh', 'Private'),
  ('JSS Academy of Technical Education Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Greater Noida Institute of Technology', 3, 'Uttar Pradesh', 'Private'),
  ('GL Bajaj Institute of Technology and Management Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('NIET Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Sharda University Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Noida International University', 3, 'Uttar Pradesh', 'Private'),
  ('Invertis University Bareilly', 3, 'Uttar Pradesh', 'Private'),
  ('MJP Rohilkhand University Bareilly', 3, 'Uttar Pradesh', 'State'),
  ('Bundelkhand University Jhansi', 3, 'Uttar Pradesh', 'State'),
  ('Sam Higginbottom University Allahabad', 3, 'Uttar Pradesh', 'Deemed'),
  ('Teerthanker Mahaveer University Moradabad', 3, 'Uttar Pradesh', 'Private'),
  ('Mangalayatan University Aligarh', 3, 'Uttar Pradesh', 'Private'),
  ('IFTM University Moradabad', 3, 'Uttar Pradesh', 'Private'),
  ('Maharishi University of Information Technology Lucknow', 3, 'Uttar Pradesh', 'Private'),
  ('Dr. APJ Abdul Kalam Technical University Lucknow', 3, 'Uttar Pradesh', 'State'),
  -- Maharashtra
  ('Bharati Vidyapeeth College of Engineering Navi Mumbai', 3, 'Maharashtra', 'Private'),
  ('Atharva College of Engineering Mumbai', 3, 'Maharashtra', 'Private'),
  ('Lokmanya Tilak College of Engineering Navi Mumbai', 3, 'Maharashtra', 'Private'),
  ('Vivekanand Education Society Institute of Technology Mumbai', 3, 'Maharashtra', 'Private'),
  ('Shah and Anchor Kutchhi Engineering College Mumbai', 3, 'Maharashtra', 'Private'),
  ('Rizvi College of Engineering Mumbai', 3, 'Maharashtra', 'Private'),
  ('MGM College of Engineering Nanded', 3, 'Maharashtra', 'Private'),
  ('Priyadarshini College of Engineering Nagpur', 3, 'Maharashtra', 'Private'),
  ('Sipna College of Engineering Amravati', 3, 'Maharashtra', 'Private'),
  ('PES Modern College of Engineering Pune', 3, 'Maharashtra', 'Private'),
  ('Marathwada Institute of Technology Aurangabad', 3, 'Maharashtra', 'Private'),
  ('Rajarambapu Institute of Technology Islampur', 3, 'Maharashtra', 'Private'),
  ('Datta Meghe College of Engineering Navi Mumbai', 3, 'Maharashtra', 'Private'),
  ('AISSMS College of Engineering Pune', 3, 'Maharashtra', 'Private'),
  ('NBN Sinhgad School of Engineering Pune', 3, 'Maharashtra', 'Private'),
  ('Dr. DY Patil Institute of Technology Pune', 3, 'Maharashtra', 'Private'),
  ('Savitribai Phule Pune University Engineering', 3, 'Maharashtra', 'State'),
  ('Government Polytechnic Mumbai', 3, 'Maharashtra', 'State'),
  ('Sandip University Nashik', 3, 'Maharashtra', 'Private'),
  ('Sanjivani College of Engineering Kopargaon', 3, 'Maharashtra', 'Private'),
  ('Dr. Babasaheb Ambedkar Technological University Lonere', 3, 'Maharashtra', 'State'),
  -- Karnataka
  ('ACS College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('Acharya Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('AMC Engineering College Bangalore', 3, 'Karnataka', 'Private'),
  ('Atria Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('Cambridge Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('City Engineering College Bangalore', 3, 'Karnataka', 'Private'),
  ('Don Bosco Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('East West Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('GATE Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('Global Academy of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('HKBK College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('ISE Bangalore', 3, 'Karnataka', 'Private'),
  ('Nagarjuna College of Engineering and Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('Oxford College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('Sapthagiri College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('Sri Venkateshwara College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('The National Institute of Engineering Mysuru', 3, 'Karnataka', 'Private'),
  ('Vidyavardhaka College of Engineering Mysuru', 3, 'Karnataka', 'Private'),
  ('Alvas Institute of Engineering and Technology Mangalore', 3, 'Karnataka', 'Private'),
  ('Canara Engineering College Mangalore', 3, 'Karnataka', 'Private'),
  ('Sahyadri College of Engineering Mangalore', 3, 'Karnataka', 'Private'),
  ('Yenepoya Institute of Technology Mangalore', 3, 'Karnataka', 'Private'),
  ('Bapuji Institute of Engineering and Technology Davangere', 3, 'Karnataka', 'Private'),
  ('Poojya Doddappa Appa College of Engineering Gulbarga', 3, 'Karnataka', 'State'),
  -- Tamil Nadu
  ('Adhiyamaan College of Engineering Hosur', 3, 'Tamil Nadu', 'Private'),
  ('Annamalai University Chidambaram', 3, 'Tamil Nadu', 'State'),
  ('Arjun College of Technology Coimbatore', 3, 'Tamil Nadu', 'Private'),
  ('Bannari Amman Institute Erode', 3, 'Tamil Nadu', 'Private'),
  ('C Abdul Hakeem College of Engineering and Technology Vellore', 3, 'Tamil Nadu', 'Private'),
  ('DMI College of Engineering Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Easwari Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Francis Xavier Engineering College Tirunelveli', 3, 'Tamil Nadu', 'Private'),
  ('GKM College of Engineering Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Jeppiaar Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Loyola ICAM College of Engineering Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Madha Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Panimalar Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Prathyusha Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('RMK Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('RMD Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Saveetha Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Sri Sairam Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Sri Venkateswara College of Engineering Sriperumbudur', 3, 'Tamil Nadu', 'Private'),
  ('Valliammai Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Vel Tech Multi Tech Engineering College Chennai', 3, 'Tamil Nadu', 'Private'),
  ('Velalar College of Engineering and Technology Erode', 3, 'Tamil Nadu', 'Private'),
  ('V.S.B. Engineering College Karur', 3, 'Tamil Nadu', 'Private'),
  ('Kamaraj College of Engineering Virudhunagar', 3, 'Tamil Nadu', 'Private'),
  ('Sethu Institute of Technology Kariapatti', 3, 'Tamil Nadu', 'Private'),
  ('P.A. College of Engineering and Technology Pollachi', 3, 'Tamil Nadu', 'Private'),
  ('K.S. Rangasamy College of Technology Tiruchengode', 3, 'Tamil Nadu', 'Private'),
  ('Nandha Engineering College Erode', 3, 'Tamil Nadu', 'Private'),
  -- Telangana & Andhra Pradesh
  ('BVRIT Hyderabad', 3, 'Telangana', 'Private'),
  ('Chaitanya Bharathi Institute of Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('CMR College of Engineering and Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('CMR Engineering College Hyderabad', 3, 'Telangana', 'Private'),
  ('Geethanjali College of Engineering and Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('JBIT Hyderabad', 3, 'Telangana', 'Private'),
  ('Keshav Memorial Institute of Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('Mahatma Gandhi Institute of Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('Methodist College of Engineering and Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('MLR Institute of Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('Nalla Malla Reddy Engineering College Hyderabad', 3, 'Telangana', 'Private'),
  ('Sreenidhi Institute of Science and Technology Hyderabad', 3, 'Telangana', 'Private'),
  ('TKR College of Engineering Hyderabad', 3, 'Telangana', 'Private'),
  ('VNR Vignana Jyothi Institute of Engineering Hyderabad', 3, 'Telangana', 'Private'),
  ('Stanley College of Engineering Hyderabad', 3, 'Telangana', 'Private'),
  ('Bhoj Reddy Engineering College for Women Hyderabad', 3, 'Telangana', 'Private'),
  ('Kakatiya Institute of Technology and Science Warangal', 3, 'Telangana', 'Private'),
  ('SR Engineering College Warangal', 3, 'Telangana', 'Private'),
  ('Koneru Lakshmaiah Education Foundation Vijayawada', 3, 'Andhra Pradesh', 'Deemed'),
  ('Prasad V. Potluri Siddhartha Institute of Technology Vijayawada', 3, 'Andhra Pradesh', 'Private'),
  ('Sree Vidyanikethan Engineering College Tirupati', 3, 'Andhra Pradesh', 'Private'),
  ('Narayana Engineering College Nellore', 3, 'Andhra Pradesh', 'Private'),
  ('QIS College of Engineering and Technology Ongole', 3, 'Andhra Pradesh', 'Private'),
  ('Lakireddy Bali Reddy College of Engineering Mylavaram', 3, 'Andhra Pradesh', 'Private'),
  ('Vignan Institute of Technology and Science Hyderabad', 3, 'Telangana', 'Private'),
  ('VR Siddhartha Engineering College Vijayawada', 3, 'Andhra Pradesh', 'Private'),
  -- Rajasthan
  ('Jaipur National University', 3, 'Rajasthan', 'Private'),
  ('Swami Keshvanand Institute of Technology Jaipur', 3, 'Rajasthan', 'Private'),
  ('Arya College of Engineering and IT Jaipur', 3, 'Rajasthan', 'Private'),
  ('Apex University Jaipur', 3, 'Rajasthan', 'Private'),
  ('Rajasthan Technical University Kota', 3, 'Rajasthan', 'State'),
  ('Government Engineering College Bikaner', 3, 'Rajasthan', 'State'),
  ('Government Engineering College Bharatpur', 3, 'Rajasthan', 'State'),
  ('Vivekananda Global University Jaipur', 3, 'Rajasthan', 'Private'),
  ('Mody University Lakshmangarh', 3, 'Rajasthan', 'Private'),
  ('Bhagwant University Ajmer', 3, 'Rajasthan', 'Private'),
  -- Gujarat
  ('Ahmedabad University', 3, 'Gujarat', 'Private'),
  ('Ganpat University Mehsana', 3, 'Gujarat', 'Private'),
  ('LDRP Institute of Technology Gandhinagar', 3, 'Gujarat', 'Private'),
  ('Atmiya University Rajkot', 3, 'Gujarat', 'Private'),
  ('Government Engineering College Modasa', 3, 'Gujarat', 'State'),
  ('Government Engineering College Rajkot', 3, 'Gujarat', 'State'),
  ('Government Engineering College Bhavnagar', 3, 'Gujarat', 'State'),
  ('Silver Oak University Ahmedabad', 3, 'Gujarat', 'Private'),
  ('Parul University Vadodara', 3, 'Gujarat', 'Private'),
  ('Navrachana University Vadodara', 3, 'Gujarat', 'Private'),
  ('C.K. Pithawala College of Engineering Surat', 3, 'Gujarat', 'Private'),
  ('Sarvajanik College of Engineering and Technology Surat', 3, 'Gujarat', 'Private'),
  ('BVM Engineering College Anand', 3, 'Gujarat', 'State'),
  -- Madhya Pradesh
  ('TIT College Bhopal', 3, 'Madhya Pradesh', 'Private'),
  ('Lakshmi Narain College of Technology Bhopal', 3, 'Madhya Pradesh', 'Private'),
  ('Oriental Institute of Science and Technology Bhopal', 3, 'Madhya Pradesh', 'Private'),
  ('Sage University Indore', 3, 'Madhya Pradesh', 'Private'),
  ('Acropolis Institute of Technology and Research Indore', 3, 'Madhya Pradesh', 'Private'),
  ('Prestige Institute of Engineering Management and Research Indore', 3, 'Madhya Pradesh', 'Private'),
  ('Institute of Engineering and Technology DAVV Indore', 3, 'Madhya Pradesh', 'State'),
  ('Madhav Institute of Technology and Science Gwalior', 3, 'Madhya Pradesh', 'State'),
  ('Jabalpur Engineering College', 3, 'Madhya Pradesh', 'State'),
  ('Chameli Devi Group of Institutions Indore', 3, 'Madhya Pradesh', 'Private'),
  ('Truba Institute of Engineering Bhopal', 3, 'Madhya Pradesh', 'Private'),
  -- West Bengal
  ('Academy of Technology Hooghly', 3, 'West Bengal', 'Private'),
  ('Asansol Engineering College', 3, 'West Bengal', 'State'),
  ('BP Poddar Institute of Management and Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Budge Budge Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Camellia Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Dr. Sudhir Chandra Sur Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Future Institute of Engineering and Management Kolkata', 3, 'West Bengal', 'Private'),
  ('Guru Nanak Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('JIS College of Engineering Kalyani', 3, 'West Bengal', 'Private'),
  ('Meghnad Saha Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Narula Institute of Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Netaji Subhash Engineering College Kolkata', 3, 'West Bengal', 'Private'),
  ('RCC Institute of Information Technology Kolkata', 3, 'West Bengal', 'Private'),
  ('Siliguri Institute of Technology', 3, 'West Bengal', 'Private'),
  ('Supreme Knowledge Foundation Group of Institutions Kolkata', 3, 'West Bengal', 'Private'),
  ('Techno India Salt Lake Kolkata', 3, 'West Bengal', 'Private'),
  ('University of Engineering and Management Jaipur', 3, 'Rajasthan', 'Private'),
  -- Bihar & Jharkhand
  ('Birsa Institute of Technology Sindri', 3, 'Jharkhand', 'State'),
  ('Cambridge Institute of Technology Ranchi', 3, 'Jharkhand', 'Private'),
  ('Jharkhand Rai University Ranchi', 3, 'Jharkhand', 'Private'),
  ('RKDF University Ranchi', 3, 'Jharkhand', 'Private'),
  ('Chandigarh Engineering College Jhanjeri', 3, 'Punjab', 'Private'),
  ('Muzaffarpur Institute of Technology', 3, 'Bihar', 'State'),
  ('National Institute of Technology Patna', 3, 'Bihar', 'State'),
  ('Darbhanga College of Engineering', 3, 'Bihar', 'State'),
  ('Gaya College of Engineering', 3, 'Bihar', 'State'),
  ('Bhagalpur College of Engineering', 3, 'Bihar', 'State'),
  ('Nalanda College of Engineering Chandi Bihar', 3, 'Bihar', 'State'),
  ('Motihari College of Engineering', 3, 'Bihar', 'State'),
  ('Bakhtiyarpur College of Engineering', 3, 'Bihar', 'State'),
  ('Supaul College of Engineering', 3, 'Bihar', 'State'),
  ('Loknayak Jai Prakash Institute of Technology Chapra', 3, 'Bihar', 'State'),
  -- Odisha
  ('Gandhi Institute of Engineering and Technology Gunupur', 3, 'Odisha', 'Private'),
  ('Gandhi Engineering College Bhubaneswar', 3, 'Odisha', 'Private'),
  ('Centurion University of Technology and Management Bhubaneswar', 3, 'Odisha', 'Private'),
  ('CV Raman Global University Bhubaneswar', 3, 'Odisha', 'Private'),
  ('Capital Engineering College Bhubaneswar', 3, 'Odisha', 'Private'),
  ('Hi-Tech Institute of Technology Bhubaneswar', 3, 'Odisha', 'Private'),
  ('Raajdhani Engineering College Bhubaneswar', 3, 'Odisha', 'Private'),
  ('Trident Academy of Technology Bhubaneswar', 3, 'Odisha', 'Private'),
  -- Kerala
  ('Albertian Institute of Science and Technology Kochi', 3, 'Kerala', 'Private'),
  ('Adi Shankara Institute of Engineering and Technology Kalady', 3, 'Kerala', 'Private'),
  ('Federal Institute of Science and Technology Kochi', 3, 'Kerala', 'Private'),
  ('Toc H Institute of Science and Technology Kochi', 3, 'Kerala', 'Private'),
  ('Ilahia College of Engineering and Technology Muvattupuzha', 3, 'Kerala', 'Private'),
  ('MES College of Engineering Kuttippuram', 3, 'Kerala', 'Private'),
  ('Vidya Academy of Science and Technology Thrissur', 3, 'Kerala', 'Private'),
  ('Marian Engineering College Trivandrum', 3, 'Kerala', 'Private'),
  ('College of Engineering Adoor', 3, 'Kerala', 'State'),
  ('College of Engineering Chengannur', 3, 'Kerala', 'State'),
  ('College of Engineering Kidangoor', 3, 'Kerala', 'State'),
  ('College of Engineering Munnar', 3, 'Kerala', 'State'),
  ('Government Engineering College Barton Hill Trivandrum', 3, 'Kerala', 'State'),
  ('Government Engineering College Idukki', 3, 'Kerala', 'State'),
  ('Government Engineering College Wayanad', 3, 'Kerala', 'State'),
  -- Punjab & Haryana
  ('Rayat Bahra University Mohali', 3, 'Punjab', 'Private'),
  ('CT University Ludhiana', 3, 'Punjab', 'Private'),
  ('Guru Nanak Dev Engineering College Ludhiana', 3, 'Punjab', 'State'),
  ('Beant College of Engineering and Technology Gurdaspur', 3, 'Punjab', 'State'),
  ('Shaheed Bhagat Singh State Technical Campus Ferozepur', 3, 'Punjab', 'State'),
  ('Baba Banda Singh Bahadur Engineering College Fatehgarh Sahib', 3, 'Punjab', 'State'),
  ('Yadavindra College of Engineering Talwandi Sabo', 3, 'Punjab', 'State'),
  ('RIMT University Mandi Gobindgarh', 3, 'Punjab', 'Private'),
  ('Maharishi Markandeshwar University Mullana', 3, 'Haryana', 'Deemed'),
  ('PDM University Bahadurgarh', 3, 'Haryana', 'Private'),
  ('Geeta Engineering College Panipat', 3, 'Haryana', 'Private'),
  ('BRCM College of Engineering and Technology Bahal', 3, 'Haryana', 'Private'),
  ('Sat Priya Group of Institutions Rohtak', 3, 'Haryana', 'Private'),
  ('Technological Institute of Textile and Sciences Bhiwani', 3, 'Haryana', 'Private'),
  ('Vaish College of Engineering Rohtak', 3, 'Haryana', 'Private'),
  ('GJU Science and Technology Hisar', 3, 'Haryana', 'State'),
  ('Maharshi Dayanand University Rohtak', 3, 'Haryana', 'State'),
  -- Himachal Pradesh & Uttarakhand
  ('Baddi University of Emerging Sciences Baddi', 3, 'Himachal Pradesh', 'Private'),
  ('Bahra University Solan', 3, 'Himachal Pradesh', 'Private'),
  ('Eternal University Baru Sahib', 3, 'Himachal Pradesh', 'Private'),
  ('AP Goyal Shimla University', 3, 'Himachal Pradesh', 'Private'),
  ('Himalayan Garhwal University Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Quantum University Roorkee', 3, 'Uttarakhand', 'Private'),
  ('Dolphin Institute of Biomedical and Natural Sciences Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Tula Institute of Technology Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Uttaranchal University Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Dev Bhoomi Uttarakhand University Dehradun', 3, 'Uttarakhand', 'Private'),
  ('GRD Institute of Management and Technology Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Roorkee Institute of Technology', 3, 'Uttarakhand', 'Private'),
  -- Chhattisgarh
  ('SSTC Bhilai', 3, 'Chhattisgarh', 'Private'),
  ('Shri Shankaracharya Technical Campus Bhilai', 3, 'Chhattisgarh', 'Private'),
  ('Chhatrapati Shivaji Institute of Technology Durg', 3, 'Chhattisgarh', 'Private'),
  ('RSR Rungta College of Engineering Bhilai', 3, 'Chhattisgarh', 'Private'),
  ('Columbia Institute of Engineering and Technology Raipur', 3, 'Chhattisgarh', 'Private'),
  ('Government Engineering College Raipur', 3, 'Chhattisgarh', 'State'),
  ('Government Engineering College Bilaspur', 3, 'Chhattisgarh', 'State'),
  -- Assam & Northeast
  ('Assam Engineering College Guwahati', 3, 'Assam', 'State'),
  ('Girijananda Chowdhury Institute of Management and Technology Guwahati', 3, 'Assam', 'Private'),
  ('Jorhat Engineering College', 3, 'Assam', 'State'),
  ('Bineswar Brahma Engineering College Kokrajhar', 3, 'Assam', 'State'),
  ('Royal Global University Guwahati', 3, 'Assam', 'Private'),
  ('Tezpur University', 3, 'Assam', 'State'),
  ('Kaziranga University Jorhat', 3, 'Assam', 'Private'),
  ('Don Bosco University Guwahati', 3, 'Assam', 'Private'),
  ('North Eastern Regional Institute of Science and Technology Itanagar', 3, 'Arunachal Pradesh', 'State'),
  ('Mizoram University Aizawl', 3, 'Mizoram', 'State'),
  ('North Eastern Hill University Shillong', 3, 'Meghalaya', 'State'),
  ('Nagaland University Dimapur', 3, 'Nagaland', 'State'),
  ('Manipur University Imphal', 3, 'Manipur', 'State'),
  ('Tripura University Agartala', 3, 'Tripura', 'State'),
  ('Sikkim Manipal Institute of Technology', 3, 'Sikkim', 'Deemed'),
  -- Goa
  ('Goa College of Engineering Farmagudi', 3, 'Goa', 'State'),
  ('Don Bosco College of Engineering Goa', 3, 'Goa', 'Private'),
  ('Padre Conceicao College of Engineering Goa', 3, 'Goa', 'Private'),
  ('Agnel Institute of Technology and Design Goa', 3, 'Goa', 'Private'),
  -- Jammu & Kashmir
  ('Government College of Engineering and Technology Jammu', 3, 'Jammu & Kashmir', 'State'),
  ('BGSBU Rajouri', 3, 'Jammu & Kashmir', 'State'),
  ('SSM College of Engineering Baramulla', 3, 'Jammu & Kashmir', 'Private'),
  ('Islamic University of Science and Technology Awantipora', 3, 'Jammu & Kashmir', 'State'),
  -- Delhi NCR additional
  ('HMR Institute of Technology and Management Delhi', 3, 'Delhi', 'Private'),
  ('Northern India Engineering College Delhi', 3, 'Delhi', 'Private'),
  ('Trinity Institute of Technology and Research Bhopal', 3, 'Madhya Pradesh', 'Private'),
  ('Axis Institute of Technology and Management Kanpur', 3, 'Uttar Pradesh', 'Private'),
  ('Azad Institute of Engineering and Technology Lucknow', 3, 'Uttar Pradesh', 'Private'),
  ('BBD University Lucknow', 3, 'Uttar Pradesh', 'Private'),
  ('DIT University Dehradun', 3, 'Uttarakhand', 'Private'),
  ('Graphic Era Hill University Dehradun', 3, 'Uttarakhand', 'Private'),
  ('IIMT College of Engineering Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('RD Engineering College Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('SRM University Delhi NCR Sonepat', 3, 'Haryana', 'Private'),
  ('KCC Institute of Technology and Management Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Dronacharya College of Engineering Gurugram', 3, 'Haryana', 'Private'),
  ('JIMS Engineering Management Technical Campus Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Krishna Engineering College Ghaziabad', 3, 'Uttar Pradesh', 'Private'),
  ('Accurate Institute of Management and Technology Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('Skyline Institute of Engineering and Technology Greater Noida', 3, 'Uttar Pradesh', 'Private'),
  ('SIT Sonipat', 3, 'Haryana', 'Private'),
  ('Lingayas Vidyapeeth Faridabad', 3, 'Haryana', 'Deemed'),
  ('MVN University Palwal', 3, 'Haryana', 'Private'),
  ('SGT University Gurugram', 3, 'Haryana', 'Private'),
  -- Additional across states for count
  ('Centurion University Visakhapatnam', 3, 'Andhra Pradesh', 'Private'),
  ('Vignan Institute of Technology and Aeronautical Engineering Hyderabad', 3, 'Telangana', 'Private'),
  ('ACE Engineering College Hyderabad', 3, 'Telangana', 'Private'),
  ('Aurora Engineering College Bhongir', 3, 'Telangana', 'Private'),
  ('Balaji Institute of Technology and Science Warangal', 3, 'Telangana', 'Private'),
  ('Guru Nanak Institutions Hyderabad', 3, 'Telangana', 'Private'),
  ('Holy Mary Institute of Technology and Science Hyderabad', 3, 'Telangana', 'Private'),
  ('JNTUH College of Engineering Sultanpur', 3, 'Telangana', 'State'),
  ('MGIT Hyderabad', 3, 'Telangana', 'Private'),
  ('Matrusri Engineering College Hyderabad', 3, 'Telangana', 'Private'),
  ('Swami Ramanand Teerth Marathwada University Nanded', 3, 'Maharashtra', 'State'),
  ('Solapur University', 3, 'Maharashtra', 'State'),
  ('Kolhapur Institute of Technology', 3, 'Maharashtra', 'Private'),
  ('Annasaheb Dange College of Engineering Sangli', 3, 'Maharashtra', 'Private'),
  ('Tatyasaheb Kore Institute of Engineering and Technology Warananagar', 3, 'Maharashtra', 'Private'),
  ('KIT College of Engineering Kolhapur', 3, 'Maharashtra', 'Private'),
  ('Finolex Academy of Management and Technology Ratnagiri', 3, 'Maharashtra', 'Private'),
  ('Amrutvahini College of Engineering Sangamner', 3, 'Maharashtra', 'Private'),
  ('SVERI College of Engineering Pandharpur', 3, 'Maharashtra', 'Private'),
  ('Sharad Institute of Technology Yadrav', 3, 'Maharashtra', 'Private'),
  ('Karmaveer Bhaurao Patil College of Engineering Satara', 3, 'Maharashtra', 'Private'),
  ('BLDEA College of Engineering and Technology Vijayapura', 3, 'Karnataka', 'Private'),
  ('Rao Bahadur Y Mahabaleswarappa Engineering College Bellary', 3, 'Karnataka', 'State'),
  ('SJB Institute of Technology Bangalore', 3, 'Karnataka', 'Private'),
  ('Sri Jayachamarajendra College of Engineering Mysuru', 3, 'Karnataka', 'State'),
  ('Mangalore Institute of Technology and Engineering', 3, 'Karnataka', 'Private'),
  ('PA College of Engineering Mangalore', 3, 'Karnataka', 'Private'),
  ('Bearys Institute of Technology Mangalore', 3, 'Karnataka', 'Private'),
  ('Malnad College of Engineering Hassan', 3, 'Karnataka', 'State'),
  ('Government Engineering College Ramanagara', 3, 'Karnataka', 'State'),
  ('Dayananda Sagar University Bangalore', 3, 'Karnataka', 'Private'),
  ('Garden City University Bangalore', 3, 'Karnataka', 'Private'),
  ('MS Engineering College Bangalore', 3, 'Karnataka', 'Private'),
  ('APS College of Engineering Bangalore', 3, 'Karnataka', 'Private'),
  ('Dr. Ambedkar Institute of Technology Bangalore', 3, 'Karnataka', 'State'),
  ('KS School of Engineering and Management Bangalore', 3, 'Karnataka', 'Private')
ON CONFLICT (name) DO NOTHING;
